// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imgeujngixksnvfceyaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZ2V1am5naXhrc252ZmNleWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDU1OTAsImV4cCI6MjA2OTE4MTU5MH0.2GnrhofMX0qF-jv-rETajnv_i0ZF0axIt80RMUsSzls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});